* Lojban Toolkit

This software contains a set of small Lojban related utilities.

** Installation

Requirements: =rust 1.43=, preferably on SIMD supported platforms

#+BEGIN_SRC bash
git clone --depth=1 https://github.com/shouya/gernytci.git
cargo install --path gernytci
#+END_SRC

** Help

#+BEGIN_SRC bash
gernytci

USAGE:
    gernytci [FLAGS] [OPTIONS] <SUBCOMMAND>

FLAGS:
    -h, --help             Prints help information
    -o, --official-only    Only entries from @official_data
    -V, --version          Prints version information

OPTIONS:
    -d, --dict <dict>    Specify custom dictionary [default: [built-in]]
    -f <format>          Output format [default: text]  [possible values: json, text]

SUBCOMMANDS:
    convert    Convert xml dump from jbovlaste (dict needs to be writable)
    cut        Decompose lujvo into tanru
    help       Prints this message or the help of the given subcommand(s)
    search     Search in dictionary
    tamsmi     Search words resembling in shape
#+END_SRC

You can checkout the usage of each subcommand via =gernytci help <subcommand>=.

** Tools

Planned features:

- [X] tamsmi - find similar word in shape
- [X] convert - convert jbovlaste dump file
- [X] search - search keyword in dictionary
- [X] cut - lujvo decomposing tool
- [X] lujvo - lujvo making tool
- [ ] grammar - beta grammar checker (camxes)
- [ ] bai - BAI <=> gismu lookup
- [ ] lookup - lookup a word in dictionary
- [ ] example - [[https://tatoeba.org/jbo/][Tatoeba]] search
- [ ] more...

** Copyright

Copyright 2020 Shou Ya

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or (at
your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see https://www.gnu.org/licenses/.
